apiVersion: v1
kind: Secret
metadata:
  name: prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster

type: Opaque

stringData:
  name: production
  server: https://api.prod.example.com:6443

  config: |
    {
      "bearerToken":"<TOKEN>",
      "tlsClientConfig":{
        "insecure":false,
        "caData":"<BASE64_CA_CERT>"
      }
    }
