apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds

type: Opaque

stringData:
  url: git@github.com:krishna-kishore-reddy
  type: git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEArO8tIPmYM9hXG7DOxWS9T/6h6fCIvichKE2VCmPjr7DZSs+a4ruO
    dh3YlK/EqZhmPcvcWNOSCsOr5DRGjWOA38K6gm0t4ugSN/pU6iXpb+QHBiSri2QgMHAw4X
    j6taipl7Har9KavsxjSS6+TETT9nUVO5HO6wsxLGTVrqU6epz6Eys8fVPVkiQUcaowum7I
    k613U9fJGlhNZ94EyQE9ZfGVL3KVW0OOGFrwD2r6dhWIil+39b3oWsuo2hJyzAg2hhDr0A
    zE/OEYiyI1bk5f/lkDdYBWkDQLdif446CH8m7g741iLtlNd8hEYH2qAYosucA9L5R4zoXh
    As6usZf6qwUbJUuqsEeFksHk1N5aule4zpbtXKfAmfo6VebdrjSgu9VCCfGQ2DRGQU0uVS
    2bKzAKbZL2gtChaHN44V4bGT48tAqfmrOVq3ImutRud17J+dRpvwuOKGjZqicMrlW5BRcX
    A4+29bWGUSISwRFxZl/QflIoMppjrbfvIvjaU5HhAAAFoGfS5eFn0uXhAAAAB3NzaC1yc2
    EAAAGBAKzvLSD5mDPYVxuwzsVkvU/+oenwiL4nIShNlQpj46+w2UrPmuK7jnYd2JSvxKmY
    Zj3L3FjTkgrDq+Q0Ro1jgN/CuoJtLeLoEjf6VOol6W/kBwYkq4tkIDBwMOF4+rWoqZex2q
    /Smr7MY0kuvkxE0/Z1FTuRzusLMSxk1a6lOnqc+hMrPH1T1ZIkFHGqMLpuyJOtd1PXyRpY
    TWfeBMkBPWXxlS9ylVtDjhha8A9q+nYViIpft/W96FrLqNoScswINoYQ69AMxPzhGIsiNW
    5OX/5ZA3WAVpA0C3Yn+OOgh/Ju4O+NYi7ZTXfIRGB9qgGKLLnAPS+UeM6F4QLOrrGX+qsF
    GyVLqrBHhZLB5NTeWrpXuM6W7VynwJn6OlXm3a40oLvVQgnxkNg0RkFNLlUtmyswCm2S9o
    LQoWhzeOFeGxk+PLQKn5qzlatyJrrUbndeyfnUab8Ljiho2aonDK5VuQUXFwOPtvW1hlEi
    EsERcWZf0H5SKDKaY6237yL42lOR4QAAAAMBAAEAAAGAK3D9pi3s5QEwiJ02o/F1ePXfGJ
    Q61YGg2635hZ2oIYdMXnWeU9yHofZHZLpurafB7z4ZwRqMsjWLJY1YN8ZKJmuVTJQ+laR0
    hylUUWlqpZfjh9CIY0CosWJNdSZd3GpdB+U+qTI/ezR+sHCUjzYvBNdOmSM8lmC+XoeKAh
    Axi4GJdG1FCbqYiNiVZiQ5j2uq6SYHNsGbHAoYj8H+87tjAAvazQt8p2tl84pMiaL2/djU
    7uWyoYGuL7i/VuCRg91/4xK4+Xr8N0V7Q7lQX7f+z2v1acuk8Z/W/3Y19aC+V5kyfwXrh4
    iw++zEjifZ3+XAuQ+AG/o2IPsAI/VdbqgR5QO7YCNUUCr3m8rS0czc/lOYFZRJultD4ttZ
    EcqZdXrEA2xeU+/jJQ2MYhorE8j9kyxfXzRwo675/6R/SUPM/boqpVaxNSaqfPKEanFnin
    rZ9sDcZbL6MQNlClmn+ikUaN4jK9iFtQmkBh/AgGxF7NZUrYk5Dj4FO1B0qCc1i3EtAAAA
    wQDBbPu/+W1OPbwk+V3oqXGiqXgivksh2lCUamoR2QHZ2TQ1Uz/284hybYzwhZUkRPBaPX
    HH9kSuOvo15MBID1PNNyi3wtZZnS/WCfCuGkd7Y9YXxvprpmUHUNoTDXIBAaeNipI5Fasc
    LJC55AYP5jozXICt4wYXl3xuGRFcMinvQX++E1d3QN2lCrxe6yXrm8uCtn8WUcG0Kxdws8
    V8IfBasgIGGjsnmNty3iFpLxoD8P0KUTV38Ue74c1HfkZs8C8AAADBANmIp3nebL0qK9RL
    E/+Q+udPqkl3AhrVvDM2DcDgiRSnon9vt5hbMSxjR0wCZwrFRbJdhixeE29z6B0l/U7D4P
    NVBw+VRAVPUse8taTw9bxt06SrX86YbuyZPt55xbMiEXHCp0KW2fMEg+8h+PIMJvj9S5D0
    3TDvNg+9bxcZJAtTX3ibMxagCbKsazujySFfNWLYOOSCaY/78O5nZi5ptsnmmvLW/MC2HC
    gtMGj2o8Hn9s9UyhoFnZtXETSH20dcuwAAAMEAy4OV7KjCW7WUOz1i0eWFcW6wvO4+7t00
    Izg+pFE/sGUbMrvFN84befCG6qVG+tFlIHrYi+hhP2SOeTCQG9G+bAryW9z9OyEhKb6H89
    zOSywts7AB0/URHJbFXaY8cb8sP5IKeEN7Pw4OLe28jHolRvVUfZwgYKyxs2QfMM4M0PF/
    jQ1Ta64qjpDPXtFTEARk33dsIx4NOU/4PaCLleCt73PI1gZoHBjCoLH6ba0TsY6rdJXbf+
    znY+l5bBJ09BATAAAAKWtyaXNobmFraXNob3JlQEtyaXNobmFzLU1hY0Jvb2stQWlyLmxv
    Y2FsAQ==
    -----END OPENSSH PRIVATE KEY-----
